language: node_js
node_js:
  - '6'
  - '8'
env:
  global: MAINRUN=true
  matrix:
    - UNDERSCORE=1.8 BACKBONE=1.3
    - LODASH=3.0 BACKBONE=1.3
    - LODASH=3.10 BACKBONE=1.3
    - LODASH=4.17 BACKBONE=1.3
before_install:
  - npm config set ca ""
install:
  - curl -L https://rawgit.com/marionettejs/travis-ci-setup/master/ci.sh | bash
script: "gulp coverage"
after_success:
  - if [[ $MAINRUN == true ]]; then npm install -g codeclimate-test-reporter; fi
  - if [[ $MAINRUN == true ]]; then codeclimate < coverage/lcov.info; fi
