language: node_js
node_js:
  - "0.10"
env:
  global: MAINRUN=true
  matrix:
    - UNDERSCORE=1.6 BACKBONE=1.0
    - UNDERSCORE=1.6 BACKBONE=1.1
    - UNDERSCORE=1.7 BACKBONE=1.1
    - UNDERSCORE=1.8 BACKBONE=1.1
    - LODASH=2.4 BACKBONE=1.1
    - LODASH=3.0 BACKBONE=1.1
    - LODASH=3.7 BACKBONE=1.1
    - UNDERSCORE=1.8 BACKBONE=1.1 MARIONETTE=2.3
    - UNDERSCORE=1.8 BACKBONE=1.1 MARIONETTE=2.4
    - LODASH=3.7 BACKBONE=1.1 MARIONETTE=2.4
before_install:
  - npm config set ca ""
install:
  - curl -L https://rawgit.com/marionettejs/travis-ci-setup/master/ci.sh | bash
script: "gulp coverage"
after_success:
  - if [[ $MAINRUN == true ]]; then npm install -g codeclimate-test-reporter; fi
  - if [[ $MAINRUN == true ]]; then CODECLIMATE_REPO_TOKEN=39acb5389290df5a87022baa6a6f8294484909b2bcc78e5bd1b534881ee768fd codeclimate < lcov.info; fi
